# Generated by Django 5.1.6 on 2025-07-16 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0022_boompump_concretesupply_equipmenthire_materialsupply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubPicture_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_sub_title_1', models.CharField(blank=True, max_length=200, null=True)),
                ('project_sub_description_1', models.TextField()),
                ('project_sub_slug_1', models.SlugField(blank=True, max_length=255, null=True)),
                ('project_sub_image_1', models.ImageField(upload_to='project_images_sub/')),
                ('project_sub_publish_date_1', models.DateTimeField(auto_now_add=True)),
                ('project_sub_author_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-project_sub_publish_date_1'],
            },
        ),
    ]
