# Generated by Django 5.1.6 on 2025-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0023_projectsubpicture_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpicture_1',
            name='sub_description_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subpicture_1',
            name='sub_description_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subpicture_1',
            name='sub_image_2',
            field=models.ImageField(default=1, upload_to='images_sub2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subpicture_1',
            name='sub_image_3',
            field=models.ImageField(default=1, upload_to='images_sub3/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subpicture_1',
            name='sub_title_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subpicture_1',
            name='sub_title_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectSubPicture_1',
        ),
    ]
