# Generated by Django 5.1.6 on 2025-07-17 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0024_subpicture_1_sub_description_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_video_description', models.TextField()),
                ('project_video_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('project_video', models.FileField(upload_to='video_sub/')),
                ('project_video_publish_date', models.DateTimeField(auto_now_add=True)),
                ('project_video_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-project_video_publish_date'],
            },
        ),
    ]
