# Generated by Django 6.0.1 on 2026-09-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0026_projectsvideomodel_delete_projectvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_company', models.CharField(blank=True, max_length=255, null=True)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='client_reviews/')),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProjectsVideoModel',
        ),
    ]
