# Generated by Django 6.1.1 on 2026-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0029_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredprojects',
            name='project_img',
            field=models.ImageField(upload_to='featured_images/'),
        ),
    ]
