# Generated by Django 6.1.1 on 2026-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0030_alter_featuredprojects_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredprojects',
            name='project_img',
            field=models.ImageField(upload_to='featured_images_2/'),
        ),
    ]
