# Generated by Django 6.1.1 on 2026-09-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0031_alter_featuredprojects_project_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutvideo',
        ),
    ]
