# Generated by Django 6.1.1 on 2026-09-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deus_magnus', '0032_delete_aboutvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredprojects',
            name='project_img_2',
            field=models.ImageField(default=1, upload_to='featured_images_2/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featuredprojects',
            name='project_img',
            field=models.ImageField(upload_to='featured_images/'),
        ),
    ]
